// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjULMs4w1YWxnHpGpMzUxmXRvl6uukw_k',
    appId: '1:782938402927:web:7a91c789ff9033378a1d9a',
    messagingSenderId: '782938402927',
    projectId: 'growwiser-3c758',
    authDomain: 'growwiser-3c758.firebaseapp.com',
    databaseURL: 'https://growwiser-3c758-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwiser-3c758.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21DyhZsP81pROqbczNgk-boI2hFfTSOU',
    appId: '1:782938402927:android:876cf40aaa128a3a8a1d9a',
    messagingSenderId: '782938402927',
    projectId: 'growwiser-3c758',
    databaseURL: 'https://growwiser-3c758-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwiser-3c758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPO4k8aLo6RH9ubm8OGC95i8zJqWfJLP0',
    appId: '1:782938402927:ios:a96ff6d477faf1e38a1d9a',
    messagingSenderId: '782938402927',
    projectId: 'growwiser-3c758',
    databaseURL: 'https://growwiser-3c758-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwiser-3c758.firebasestorage.app',
    iosBundleId: 'com.example.growWiser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPO4k8aLo6RH9ubm8OGC95i8zJqWfJLP0',
    appId: '1:782938402927:ios:a96ff6d477faf1e38a1d9a',
    messagingSenderId: '782938402927',
    projectId: 'growwiser-3c758',
    databaseURL: 'https://growwiser-3c758-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwiser-3c758.firebasestorage.app',
    iosBundleId: 'com.example.growWiser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjULMs4w1YWxnHpGpMzUxmXRvl6uukw_k',
    appId: '1:782938402927:web:a34f038f19050b708a1d9a',
    messagingSenderId: '782938402927',
    projectId: 'growwiser-3c758',
    authDomain: 'growwiser-3c758.firebaseapp.com',
    databaseURL: 'https://growwiser-3c758-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'growwiser-3c758.firebasestorage.app',
  );
}
